### ISSUE TITLE
Extremely slow upload speeds

### ISSUE THREAD

**Issue by alscaldas** [fletchto99/nicotine-plus-docker#12]
Maybe I'm doing something completely stupid, but I just can't figure out why my upload speeds are so slow (1.5 Kib/s slowing to 0).

I'm using an OPNsense firewall and connecting to AirVPN via Wireguard.

I'm quite sure the forwarding part works both because https://www.slsknet.org/porttest.php?port=16182 shows it as opened and also because I use other services (qBittorrent being an example) and get acceptable download and upload speeds. But I just can't make it work with nicotine-plus.

Besides forwarding only the listening port I also unsuccessfully tried to forward a range of ports (so that I could forward 2234-2236 to, say, 16183-16185. AirVPN only allows 5 forwarded ports total).

```yml
services:
  nicotine-plus:
    #image: ghcr.io/fletchto99/nicotine-plus-docker:latest
    image: fletchto99/nicotine-plus-docker:latest
    container_name: nicotine-plus
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
      - PASSWORD= #optional
      - LISTENING_PORT=16182
    volumes:
      - /home/myuser/docker/nicotine/config:/config
      - /mnt/nicotine/Downloads:/data/downloads
      - /mnt/nicotine/Incompletos:/data/incomplete_downloads
      - /mnt/musicas:/data/shared:ro
    ports:
      #- 6080:6080
      - 16182:16182
      - 2234-2239:2234-2239
    restart: unless-stopped
```

I'd appreciate any suggestions on what I may be doing wrong.
