### ISSUE TITLE
How to add plugin?

### ISSUE THREAD

**Issue by zengateway** [fletchto99/nicotine-plus-docker#7]
Hello! How i can add plugin? Especially [this one Leech Banner](https://github.com/dakka/leech_banner)

**Comment by zengateway** [comment]
In case anyone wants to know, there is a path ~/.local/share/nicotine/plugins/

**Comment by lukyjay** [comment]
> In case anyone wants to know, there is a path ~/.local/share/nicotine/plugins/

Just to further clarify this comment, it is /config/.local/share/nicotine/plugins/

So my docker compose looks like this (see last line of the Volumes section)
```
services:
  nicotine-plus:
    image: ghcr.io/fletchto99/nicotine-plus-docker:3.3.10@sha256:3ff1985eb1c478bf24cc8667ab8dacb2aaefefc5b60a7b65a2162b67c8454ac7
    container_name: nicotine-plus
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - /opt/docker/downloads/nicotine:/config
      - /pve1storage/Media/TV:/pve1storage/Media/TV
      - /pve1storage/Media/Downloads:/pve1storage/Media/Downloads
      - /opt/docker/nicotine/plugins:/config/.local/share/nicotine/plugins/
    ports:
      - 6080:6080
      - 2234-2239:2234-2239
    restart: unless-stopped
```
